# Generated by Django 6.0.3 on 2026-03-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders')),
                ('phone_number', models.CharField(max_length=15)),
                ('id_no', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('year_discharged', models.ImageField(upload_to='')),
            ],
        ),
    ]
